apiVersion: apps/v1
kind: Deployment
metadata:
  name: fault-injector-service
  namespace: fault-injection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fault-injector-service
  template:
    metadata:
      labels:
        app: fault-injector-service
    spec:
      serviceAccountName: fault-injector-sa
      containers:
        - name: fault-injector
          image: faultinjector
          ports:
            - containerPort: 8080
              name: server
            - containerPort: 5005
              name: debug
          env:
            - name: TZ
              value: "Europe/Berlin"

---

apiVersion: v1
kind: Service
metadata:
  name: fault-injector-service
  namespace: fault-injection
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: server
    - port: 5005
      targetPort: 5005
      name: debug
  selector:
    app: fault-injector-service

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: fault-injector-sa
  namespace: fault-injection

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: fault-injection
  name: fault-injector-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "update"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fault-injector-rolebinding
  namespace: fault-injection
subjects:
  - kind: ServiceAccount
    name: fault-injector-sa
    namespace: fault-injection
roleRef:
  kind: Role
  name: fault-injector-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: fault-injector-role-default
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "update"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fault-injector-rolebinding-default
  namespace: default
subjects:
  - kind: ServiceAccount
    name: fault-injector-sa
    namespace: fault-injection
roleRef:
  kind: Role
  name: fault-injector-role-default
  apiGroup: rbac.authorization.k8s.io
