apiVersion: apps/v1
kind: Deployment
metadata:
  name: fault-injector-service
  namespace: fault-injection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fault-injector-service
  template:
    metadata:
      labels:
        app: fault-injector-service
    spec:
      containers:
        - name: fault-injector
          image: faultinjector
          ports:
            - containerPort: 8080
              name: server
            - containerPort: 5005
              name: debug

---

apiVersion: v1
kind: Service
metadata:
  name: fault-injector-service
  namespace: fault-injection
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: server
    - port: 5005
      targetPort: 5005
      name: debug
  selector:
    app: fault-injector-service
