apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: logging
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          node: ${NODE_NAME}
          templates:
            - condition:
                and:
                  - or:
                      - equals:
                          kubernetes.namespace: "default"
                      - equals:
                          kubernetes.namespace: "fault-injection"
                  - not:
                      equals:
                        kubernetes.container.name: "istio-proxy"
              config:
                - type: container
                  paths:
                    - /var/log/containers/*${data.kubernetes.container.id}.log

    processors:
      - add_kubernetes_metadata:
          in_cluster: true
    output.elasticsearch:
      hosts: [ "elasticsearch.logging:9200" ]
