apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: jaeger
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:latest
          ports:
            - containerPort: 9411
            - containerPort: 16686
            - containerPort: 14268
            - containerPort: 14250
          env:
            - name: SPAN_STORAGE_TYPE
              value: elasticsearch
            - name: ES_SERVER_URLS
              value: http://elasticsearch.logging:9200
            - name: COLLECTOR_ZIPKIN_HOST_PORT
              value: "9411"
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: istio-system
spec:
  ports:
    - name: zipkin
      port: 9411
      protocol: TCP
      targetPort: 9411
    - name: query
      port: 16686
      protocol: TCP
      targetPort: 16686
    - name: collector
      port: 14268
      protocol: TCP
      targetPort: 14268
    - name: collector-grpc
      port: 14250
      protocol: TCP
      targetPort: 14250
  selector:
    app: jaeger
  type: ClusterIP
