apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-config
  namespace: logging
data:
  metricbeat.yml: |
    setup.template.settings:
      index.number_of_shards: 1
      index.codec: best_compression
    metricbeat.autodiscover:
      providers:
        - type: kubernetes
          scope: cluster
          node: ${NODE_NAME}
          hints.enabled: false
          templates:
            - config:
                - module: prometheus
                  period: 5s
                  hosts: ["https://${NODE_NAME}:10250"]
                  metrics_path: /metrics/cadvisor
                  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
                  ssl.certificate_authorities:
                    - /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    output.elasticsearch:
      hosts: ["elasticsearch.logging:9200"]
    processors:
      - drop_event:
          when:
            not:
              equals:
                prometheus.labels.namespace: "default"
